language: go

go:
  - 1.4

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/go-diff
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/go-diff
  - cd $TRAVIS_BUILD_DIR

install:
  - go get golang.org/x/tools/cmd/vet

script:
  - export TZ=US/Pacific # TODO: Fix this.
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d ./)
  - go tool vet ./
  - go test -v -race ./...
